workspace:
  - workspace.rs
  - workspace/*
  - workspace/**/*

repository:
  - workspace/repository.rs
  - workspace/repository_tests.rs

commit:
  - workspace/commit.rs
  - workspace/commit_tests.rs

release:
  - workspace/release.rs
  - workspace/release_tests.rs

ci:
  - .github/*
  - .github/**/*
